name: Make twrp-12.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Remove Useless Package
      run: |
        sudo apt -y autoclean
        sudo apt clean
        sudo apt update
        sudo apt upgrade -y
        sudo apt dist-upgrade -y
        sudo apt full-upgrade -y
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Check Out
      uses: actions/checkout@4

    - name: Set output
      run: echo "name=date::$(date +%F)"
      id: var

    - name: Prepare Environment
      run: |
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2 
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo bash setup/install_android_sdk.sh || true
    - name: Init Repo
      run: |
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
    - name: Repo Sync
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        repo sync -j$(nproc --all)
        ls -al
    - name: Repopick Patches
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        repopick 5405
        repopick 5540
        repopick 5493
        repopick 5639
        repopick 5653
        repopick 5675
        repopick 5689
        repopick 5691
        repopick 5693
        repopick 5694
        repopick 5696
        repopick 5724
        repopick 5743
    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        git clone https://github.com/D8100-9000-TWRP-Device-Tree/device_xiaomi_xaga-TWRP.git -b twrp-12.1_A13 ./device/xiaomi/xaga
    - name: Building
      run: |
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        lunch twrp_xaga-eng
        mka vendorbootimage -j$(nproc --all)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: xaga_twrp-12.1
        path: workspace/out/target/product/xaga/*.img
